config/routes.rb
Rails.application.routes.draw do

  resources :interview_reminders do
  member do
    get :done ,:question
    end
  end

  resources :portals do 
    member do
      get :shedule_interview
    end
  end
# get "question" "done/question"

  root 'home#index'



  devise_for :users do
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/interview_reminder.rb
class InterviewReminder < ApplicationRecord
	validates_uniqueness_of :interview_date, scope: :user
	belongs_to :user
end

app/controllers/interview_reminders_controller.rb
class InterviewRemindersController < ApplicationController
  before_action :set_interview_reminder, only: %i[ show edit update destroy ]

  before_action :authenticate_user!

  # GET /interview_reminders or /interview_reminders.json
  def index
    @interview_reminders = InterviewReminder.all
  end

  # GET /interview_reminders/1 or /interview_reminders/1.json
  def show
  end

  # GET /interview_reminders/new
  def new
    @interview_reminder = InterviewReminder.new
  end

  # GET /interview_reminders/1/edit
  def edit
  end

  # POST /interview_reminders or /interview_reminders.json
  def create
    @interview_reminder = InterviewReminder.new(interview_reminder_params)

    # debugger
    # MailServiceMailer.one_hour(@interview_reminder).deliver_now

    # debugger
    # MailServiceMailer.one_hour(@interview_reminder).deliver_now


    respond_to do |format|
      if @interview_reminder.save
        format.html { redirect_to interview_reminder_url(@interview_reminder), notice: "Interview reminder was successfully created." }
        format.json { render :show, status: :created, location: @interview_reminder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @interview_reminder.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /interview_reminders/1 or /interview_reminders/1.json
  def update
    respond_to do |format|
      if @interview_reminder.update(interview_reminder_params)
        format.html { redirect_to interview_reminder_url(@interview_reminder), notice: "Interview reminder was successfully updated." }
        format.json { render :show, status: :ok, location: @interview_reminder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @interview_reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interview_reminders/1 or /interview_reminders/1.json
  def destroy
    @interview_reminder.destroy

    respond_to do |format|
      format.html { redirect_to interview_reminders_url, notice: "Interview reminder was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def done
      @interview_reminder = InterviewReminder.find_by(id:params[:id])
      @interview_reminder.update(status:true)
      # MailServiceMailer.done(@interview_reminder).deliver_now
      redirect_to interview_reminder_path

  end  

def question

  @interview_reminder = InterviewReminder.find_by(id:params[:id])
 if @interview_reminder.update(status:true)

 
        # debugger    
     @interview_reminder = InterviewReminder.update(user_id: @portal.user_id, question: @interview_reminder.question)

     # @interview_reminder = InterviewReminder.find_by(id:params[:id])

     redirect_to interview_reminders_path
    else
      render :new
  end

  
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview_reminder
      @interview_reminder = InterviewReminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interview_reminder_params
      params.require(:interview_reminder).permit(:company_name, :applied_by, :interview_date, :duration, :interview_round, :question,:user_id)


      # params.require(:interview_reminder).permit(:company_name, :applied_by, :interview_date, :duration, :interview_round, :question)
      params.require(:interview_reminder).permit(:company_name, :interview_date, :status, :questions,:remark)

    end
end

app/helpers/interview_reminders_helper.rb
module InterviewRemindersHelper
end

app/views/interview_reminders/_form.html.erb
<%= form_with(model: interview_reminder) do |form| %>
  <% if interview_reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interview_reminder.errors.count, "error") %> prohibited this interview_reminder from being saved:</h2>

      <ul>
        <% interview_reminder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>

    <%# debugger %>
    <%= form.label :company_name %>
    <%= form.text_field :company_name%>
  </div>


<%= form.select :user, User.all.collect {|p| [ p.email, p.id ] } %>

  <div class="field">
    <%= form.label :applied_link%>
    <%= form.text_field :applied_from %>
  </div>


  <div class="field">
    <%= form.label :interview_date %>
    <%= form.datetime_field :interview_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :interview_round %>
    <%= form.text_field :interview_round %>
  </div>

  <div class="field">
    <%#= form.label :question %>
    <%#= form.cktext_area :question %>
  </div>
<!-- 
<div class="field">
<b>Status:</b>
<%#= form.label :status, "Applied"  %>
<%#= form.radio_button :status, true %>
<%#= form.label :status, "Not Applied" %>
<%#= form.radio_button :status, false %>
</div></br> -->



  <div class="field">
    <%= form.number_field :user_id,id: :interview_reminder_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/interview_reminders/edit.html.erb
<h1>Editing Interview Reminder</h1>

<%= render 'form', interview_reminder: @interview_reminder %>

<%= link_to 'Show', @interview_reminder %> |
<%= link_to 'Back', interview_reminders_path %>

app/views/interview_reminders/index.html.erb
<p id="notice"><%= notice %></p>

<style type="text/css">
/*    .container {
    width: 1080px;
    margin: 20px auto;
    background-color: #fefefe;
    color: #222;
    padding: 20px;
  }*/

    table {
    border-spacing: 0;
    border-collapse: collapse;
    width: 100%;
    text-align: center;
    line-height: 150%;
    border-radius: 4px;
    background-color: #EAFAF1;
    box-shadow: 0 0 6px #666666;
  }
</style>

<div><h1>Interview Reminders</h1></div>
<div class="container">

<table class="table table-striped responsive text-center">
  <thead>
    <tr>
      <th>Company name</th>
      <th>Applied by</th>
      <th>Interview date</th>
      <th>Duration</th>
      <th>Interview round</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interview_reminders.each do |interview_reminder| %>
      <tr>
        <td><%= interview_reminder.company_name %></td>
        <td><%= interview_reminder.applied_by %></td>

        <td><%#= interview_reminder.interview_date.strftime("%Y-%m-%d %I:%M") %></td>

        <td><%= interview_reminder.interview_date %></td>

        <td><%= interview_reminder.duration %></td>
        <td><%= interview_reminder.interview_round %></td>
        <td><%= interview_reminder.question %></td>
        <td><%= link_to 'Show', interview_reminder,class:"btn btn-primary" %></td>
      <% if interview_reminder.status == false%>
        <td><%= link_to 'Destroy', interview_reminder, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        <td><%= link_to 'Reschedule interview', edit_interview_reminder_path(interview_reminder), class:"btn btn-primary " %></td>
        <td><%= link_to 'Done', done_interview_reminder_path(interview_reminder),  data: { confirm: 'Are you sure Interview has been taken ?' }, class:"btn btn-success " %></td>
         <%else%>
         <td></td>
         <td></td>
         <td></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

<br>
<div>

  <%= link_to 'Home',root_path, class:"btn btn-outline-primary" %>

</div>
<div>
<%= link_to 'New Interview Reminder', new_interview_reminder_path, class:"btn btn-outline-primary"  %>
</div>
</div>

<td><%#= user.email %></td>

app/views/interview_reminders/new.html.erb
<h1>New Interview Reminder</h1>

<%= render 'form', interview_reminder: @interview_reminder %>

<%= link_to 'Back', interview_reminders_path %>

app/views/interview_reminders/show.html.erb
<!-- <p id="notice"><%= notice %></p>
<div class="container">
<table class="table table-striped responsive text-center" >  -->
    <div class="card text-center">
  <div class="card-header">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="card-body">
    
<p>
  <strong>Company name:</strong>
  <%= @interview_reminder.company_name %>
</p>

<p>
  <strong>Applied by:</strong>
  <%= @interview_reminder.applied_by %>
</p>

<p>
  <strong>Interview date:</strong>
  <%= @interview_reminder.interview_date.strftime("%Y-%m-%d %I:%M") %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @interview_reminder.duration %>
</p>

<p>
  <strong>Interview round:</strong>
  <%= @interview_reminder.interview_round %>
</p>

<p>
  <strong>Question:</strong>
  <%= @interview_reminder.question %>
</p>

<%= link_to 'Reschedule interview', edit_interview_reminder_path(@interview_reminder), class:"btn btn-outline-success " %> |
<%= link_to 'Back', interview_reminders_path , class:"btn btn-outline-primary"%>
</table>

<div>
  </div>
  <div class="card-footer text-muted">
    @railskart.com
  </div>
</div>