config/routes.rb
Rails.application.routes.draw do

  resources :interview_reminders do
  member do
    get :done ,:question
    end
  end

  resources :portals do 
    member do
      get :shedule_interview
    end
  end
# get "question" "done/question"

  root 'home#index'



  devise_for :users do
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portal.rb
class Portal < ApplicationRecord

	# has_one :interview_reminder
	validates_uniqueness_of :date_of_application, scope: :user 
	

	 validates :company_name,:status,:date_of_application, presence: true
    belongs_to :user

end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portal, only: %i[ show edit update destroy ]

  # GET /portals or /portals.json
  def index
 
    @portals = Portal.all.where(id: current_user.portal_ids)
    
  end

  # GET /portals/1 or /portals/1.json
  def show
  end

  # GET /portals/new
  def new
    @portal = Portal.new
  end

  # GET /portals/1/edit
  def edit
  end

  # POST /portals or /portals.json
  def create
    @portal = Portal.new(portal_params)

    respond_to do |format|
      if @portal.save
        format.html { redirect_to portal_url(@portal), notice: "Portal was successfully created." }
        format.json { render :show, status: :created, location: @portal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portals/1 or /portals/1.json
  def update
    respond_to do |format|
      if @portal.update(portal_params)
        format.html { redirect_to portal_url(@portal), notice: "Portal was successfully updated." }
        format.json { render :show, status: :ok, location: @portal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portals/1 or /portals/1.json
  def destroy
    @portal.destroy

    respond_to do |format|
      format.html { redirect_to portals_url, notice: "Portal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def shedule_interview

  @portal = Portal.find_by(id:params[:id])
if @portal.update(status:true)
        # debugger    
     @interview_reminder = InterviewReminder.create!(user_id: @portal.user_id, company_name: @portal.company_name)

     # @interview_reminder = InterviewReminder.find_by(id:params[:id])

     redirect_to  edit_interview_reminder_path @interview_reminder
    else
      render :new
  end
end


 # def approve
 #    # debugger
 #      @portal = Portal.find_by(id:params[:id])
 #      # debugger
 #      if @portal.update(status:true)
 #        # debugger    
 #     @interview_reminder = InterviewReminder.create!(user_id: @portal.user_id, start: @portal.login_time)
 #     # MailServiceMailer.approve_atten_req(@portal).deliver_now
 #      redirect_to portals_path
 #    else
 #      render :new
 #    end
 #  end 





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portal
      @portal = Portal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portal_params


      params.require(:portal).permit(:company_name, :applied_from, :applied_from_link, :date_of_application, :status, :user_id)

    end
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/portals/_form.html.erb
<html>
<%= form_with(model: portal) do |form| %>
  <% if portal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portal.errors.count, "error") %> prohibited this portal from being saved:</h2>

      <ul>
        <% portal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name, "Company Name:"%>
    <%= form.text_field :company_name %>
  </div></br>

  <div class="field">
    <%= form.label :applied_from, "Applied From:" %>
    <%= form.select :applied_from, [['Other','Other'],['LinkedIn','LinkedIn'],['Job Portal','Job Portal'],['Company Website','Company Website']] %>
    <%= form.label :applied_from_link, "Applied Link:" %>
    <%= form.text_field :applied_from_link %>
    

  </div></br>

  <div class="field">
    <%= form.label :date_of_application, "Date Of Application:" %>
    <%= form.date_select :date_of_application %>
  </div></br>

  <div class="field">
    <b>Status:</b>
    <%= form.label :status, "Applied"  %>
    <%= form.radio_button :status, true %>
    <%= form.label :status, "Not Applied" %>
    <%= form.radio_button :status, false %>
  </div></br>



<div class="field">
    <%= form.number_field :user_id,id: :portal_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>



  <div class="field">
    <%= form.number_field :user_id,id: :portal_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div></br>
<% end %>
</html>


<script>
$(function() {
  function selectVisibility() {
    var selector = $($(this).attr('data-selects-visibility'));
    if ($(this).is('input[type="checkbox"]')) {
      if ($(this).is(':checked')) {
        value = '_checked';
      } else {
        value = '_unchecked';
      }
    } else if ($(this).is('input[type=radio]')) {
      var checkedRadioButton = $(this).closest('form').find('input[type="radio"][name="' + $(this).attr('name') + '"]:checked');
      if (checkedRadioButton.length > 0) {
        value = checkedRadioButton.val();
      }
    } else {
      var value = $(this).val();
    }
    if (!value) {
      value = '_blank';
    }
    selector.filter('[data-show-for]:not([data-show-for~="' + value + '"])').hide();
    selector.filter('[data-hide-for~="' + value + '"]').hide();
    selector.filter('[data-hide-for]:not([data-hide-for~="' + value + '"])').show();
    selector.filter('[data-show-for~="' + value + '"]').show();
  }

  $(this).find('[data-selects-visibility]').change(selectVisibility);
  $(this).find('select[data-selects-visibility]').each(selectVisibility);
  $(this).find('input[data-selects-visibility][type="checkbox"]').each(selectVisibility);
  $(this).find('input[data-selects-visibility][type="radio"]:checked').each(selectVisibility);
});
</script>

app/views/portals/edit.html.erb
<h1>Editing Railskart Portal</h1>

<%= render 'form', portal: @portal %>

<%= link_to 'Show', @portal %> |
<%= link_to 'Back', portals_path %>

app/views/portals/index.html.erb
<div id="railskart_portals">


<style type="text/css">
/*    .container {
    width: 1080px;
    margin: 20px auto;
    background-color: #fefefe;
    color: #222;
    padding: 20px;
  }*/

    table {
    border-spacing: 0;
    border-collapse: collapse;
    width: 100%;
    text-align: center;
    line-height: 150%;
    border-radius: 4px;
    background-color: #EAFAF1;
    box-shadow: 0 0 6px #666666;
  }
</style>
<div>
  <div class="card-header text-center">
  <h1>Railskart Portals</h1>
</div></br>
<div class="container">
<table class="table table-striped responsive text-center">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Applied From</th>
      <th>Applied Link</th>
      <th>Date Of Application</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portals.each do | portal| %>
    <tr>
        <td><%= portal.company_name %></td>
        <td><%= portal.applied_from %></td>
        <td><%= link_to 'Visit Url', "http://#{portal.applied_from_link}", class:"btn btn" %></td>
        <td><%= portal.date_of_application %></td>
        <td> <% if portal.status == true %>
                Applied
                <%else%>
                Not Applied
                <%end%>
        </td>
        <td><%= link_to "SHOW", portal,class:"btn btn-primary" %></td>
        <td><%= link_to "Shedule interview",shedule_interview_portal_path(portal), data: { confirm: 'Shedule A Interview ?' },class: "btn btn-primary" %> </td>
      </tr>
        
  </tbody>
    <% end %>
</table>
<br/>




<div class="card-footer text-center">
  <%= link_to 'New Railskart Portal', new_portal_path, class:"btn btn-primary" %>
</div>



    <div>
  <%= link_to 'Home',root_path, class:"btn btn-outline-primary" %>
</div>

app/views/portals/new.html.erb
<h1>New Portal</h1>

<%= render 'form', portal: @portal %>

<%= link_to 'Back', portals_path %>

app/views/portals/show.html.erb
<html>
<p id="notice"><%= notice %></p>
<div class="col-lg-8 ">
  <div class="card" style="width: 50rem;">
  <div class="card-header text-center">
    Railskart Portal
  </div>
  <div class="card shadow">
  <div class="card-body">
<p>
  <strong>Company Name:</strong>
  <%= @portal.company_name %>
</p>

<p>
  <strong>Applied From:</strong>
  <%= @portal.applied_from %>
</p>

<p>
  <strong>Applied Link:</strong>
  <%= link_to 'Visit Url', "http://#{@portal.applied_from_link}" %>
</p>

<p>
  <strong>Date Of Application:</strong>
  <%= @portal.date_of_application %>
</p>

<p>
  <strong>Status:</strong>
  <% if @portal.status == true %> 
             Applied
             <%else%>
             Not Applied
             <%end%>
</p>

  <div class="card-footer text-muted">
    <div class="d-flex justify-content-center">
    <span class="mx-2">  
    <%= link_to "EDIT", edit_portal_path(@portal), class:"btn btn-primary" %>
    </span>
    <span class="mx-2">
    <%= link_to "BACK", portals_path, class:"btn btn-primary" %>
    </span>
    <span class="mx-2">
    <%= button_to "DESTROY", @portal, method: :delete, class:"btn btn-primary" %>
    </span>
    </div>
  </div>

</div>
</div>
</html>